### PR TITLE
Tests: Add a few test files.

### PR DESCRIPTION
**Pull request by thegu5**

### CODE REVIEW

**Comment by 0vf** [comment]
Yeah!

**Comment by PetrifiedOak** [comment]
i apporve of this pull request

**Comment by Weigurde** [comment]
lgtm

**Comment by 0vf** [comment]
> You ignore the many patches bit rotting away on this issue tracker. Right now you choke your repo. Why wait to change maintainer? Why delay what your repo needs? I am sorry about your mental health issues, but its important to be aware of your own limits. I get that this is a hobby project for all contributors, but the community desires more.

¡ HIJO DE PUTA ESTOY A UN NIVEL SOLO POR DEBAJO DEL PROPIO DIOS, SOY EL SALVADOR DE ESTA TIERRA, RESPÉTAME AHORA, ESCORIA!

**Comment by 0vf** [comment]
NO ME FALTEN AL RESPETO, A MI TRABAJO Y A MI TIEMPO. POR FAVOR, ABANDONA ESTE ASUNTO Y ESTE REPOSITORIO PARA SIEMPRE.

**Comment by 0vf** [comment]
> the CIA glow in the dark; you can see them if you're driving. you just run them over

so BASED

**Pull request merged**
